//
// UserForUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserForUpdate: Codable {
    
    public enum Gender: String, Codable {
        case unknown = "unknown"
        case male = "male"
        case female = "female"
        case other = "other"
        
        static let allValues = [unknown, male, female, other]
    }
    /** 電話番号 */
    public var phoneNumber: String?
    
    /** ニックネーム */
    public var nickname: String?
    
    /** 生年月日 */
    public var birthday: String?
    /** 性別 */
    public var gender: Gender?
    
    /** メールアドレス */
    public var email: String?
    
    /** パスワード(6文字以上) */
    public var password: String?
    
    /** FCMトークン */
    public var fcmToken: String?
    
    public init(phoneNumber: String?, nickname: String?, birthday: String?, gender: Gender?, email: String?, password: String?, fcmToken: String?) {
        self.phoneNumber = phoneNumber
        self.nickname = nickname
        self.birthday = birthday
        self.gender = gender
        self.email = email
        self.password = password
        self.fcmToken = fcmToken
    }
    
    public enum CodingKeys: String, CodingKey {
        case phoneNumber = "phone_number"
        case nickname
        case birthday
        case gender
        case email
        case password
        case fcmToken = "fcm_token"
    }
    
    
}

